database:
  container_name: database
  image: percona:5.7
  environment:
    MYSQL_DATABASE: ${DB_NAME}
    MYSQL_USER: ${DB_USERNAME}
    MYSQL_PASSWORD: ${DB_PASSWORD}
    MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  env_file:
    - .env
  restart: always
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  ports:
    - "3308:3306"

flyway:
  container_name: flyway
  image: boxfuse/flyway
  restart: always
  env_file:
    - .env
  command: -url=jdbc:mysql://${DB_HOST}:3306?verifyServerCertificate=false&useSSL=true -schemas=${DB_NAME} -user=${DB_USERNAME} -password=${DB_PASSWORD} clean migrate
  volumes:
    - "./src/main/resources/db/migration:/flyway/sql"
  links:
    - database

app:
  build: .
  dockerfile: docker/Dockerfile
  ports:
    - "8085:8080"
  env_file:
    - .env
  environment:
    - SPRING_PROFILES_ACTIVE=dev
  links:
    - database