spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://database:3306/katniss
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver_class: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true